// Generated by ToffeeScript 1.6.3-4
var add, migo, migrate, _ref,
  _this = this;

migo = require('..');

_ref = migo.init({
  dbname: 'migo_test',
  sslmode: false
}), add = _ref.add, migrate = _ref.migrate;

add('create table foo', {
  up: "CREATE TABLE foo(\n    id Serial,\n    name Text\n)",
  down: function(autocb) {
    var _this = this;
    this.drop('foo', function(_$$_0) {
      autocb(_$$_0);
    });
  }
});

add('add index', {
  up: 'CREATE INDEX ON foo(name)'
});

migrate(process.argv[2], function(_$$_1) {
  return _$$_1;
});
